"""Official Python SDK for the Screenshot Scout screenshot API."""

from .client import AsyncScreenshotScoutClient, RequestTimeout, ScreenshotScoutClient
from .errors import (
    ScreenshotScoutAPIError,
    ScreenshotScoutConfigurationError,
    ScreenshotScoutError,
    ScreenshotScoutResponseDecodingError,
    ScreenshotScoutSerializationError,
    ScreenshotScoutTransportError,
)
from .models import (
    BinaryCaptureResponse,
    CaptureColorScheme,
    CaptureFormat,
    CaptureHTTPMethod,
    CaptureImageAnchor,
    CaptureImageMode,
    CaptureMediaType,
    CaptureOptions,
    CapturePdfPaperFormat,
    CaptureResponse,
    CaptureResponseType,
    CaptureResult,
    CaptureStorageMode,
    CaptureWaitUntil,
    JsonCaptureResponse,
    RawResponse,
)

__all__ = [
    "AsyncScreenshotScoutClient",
    "BinaryCaptureResponse",
    "CaptureColorScheme",
    "CaptureFormat",
    "CaptureHTTPMethod",
    "CaptureImageAnchor",
    "CaptureImageMode",
    "CaptureMediaType",
    "CaptureOptions",
    "CapturePdfPaperFormat",
    "CaptureResponse",
    "CaptureResponseType",
    "CaptureResult",
    "CaptureStorageMode",
    "CaptureWaitUntil",
    "JsonCaptureResponse",
    "RawResponse",
    "RequestTimeout",
    "ScreenshotScoutAPIError",
    "ScreenshotScoutClient",
    "ScreenshotScoutConfigurationError",
    "ScreenshotScoutError",
    "ScreenshotScoutResponseDecodingError",
    "ScreenshotScoutSerializationError",
    "ScreenshotScoutTransportError",
]
